# Generated by Django 5.0.3 on 2024-07-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=200)),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('XL', 'Xl'), ('XXL', 'XXL')], max_length=50)),
                ('category', models.CharField(choices=[('men', 'men'), ('women', 'women'), ('kids', 'kids'), ('FEATUREDPRODUCT', 'FEATURED PRODUCT'), ('NEWPRODUCTS', 'NEWPRODUCTS'), ('INSPIREDPRODUCTS', 'INSPIREDPRODUCTS')], max_length=50)),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
